#!/bin/sh

if [ $# -ne 1 ]
then
  echo "Usage: sh checkpack \"PLATFORM\""
  echo "Example: sh checkpack 143_6M"
  exit
fi

PLATFORM=$1
PKGROOT="/home/"
PKGPATH=${PKGROOT}${PLATFORM}

packages="
bash expat gmake isc-dhcp44-server libtool autoconf memcached libmemcached redis mysql80-client mysql80-server apache24
php85 mod_php85 php85-bcmath php85-ctype php85-curl php85-dom php85-extensions php85-filter php85-ftp php85-gd 
php85-iconv php85-mbstring php85-mysqli php85-opcache php85-pdo php85-pdo_sqlite
php85-phar php85-posix php85-session php85-simplexml php85-snmp php85-soap php85-sockets php85-sqlite3 php85-tokenizer
php85-xml php85-xmlreader php85-xmlwriter php85-zip php85-zlib php85-pecl-memcached php85-pecl-redis graphviz softflowd
sqlite3 sudo vim-tiny wget arping bandwidthd elinks mc nano nmap mtr-nox11 expect bwm-ng ifstat iperf iperf3 arpwatch
ap24-mod_rpaf2 git ffmpeg nginx bmon iftop bind-tools trafshow fping freeradius3 net-snmp curl 
"

for pkg in $packages; do
    if ls "$PKGPATH"/"$pkg"-*.pkg >/dev/null 2>&1; then
        echo "✅ Package $pkg [OK]"
    else
        echo "❌ Package $pkg [MISSING]"
    fi
done
