#!/bin/sh

if [ $# -ne 1 ]
then
  echo "Usage: sh packagepack_ver \"PLATFORM\""
  echo "Example: sh packagepack_143M 143_6M"
  exit
fi

#bootstraping pkgng
pkg info

PLATFORM=$1
PKGROOT="/home/"
PKGPATH=${PKGROOT}${PLATFORM}
ARCHNAME=${PLATFORM}".tar.gz"

mkdir ${PKGPATH}

#installing packages
pkg install -y bash
pkg install -y expat
pkg install -y gmake
pkg install -y isc-dhcp44-server
pkg install -y libtool
pkg install -y autoconf
pkg install -y memcached
pkg install -y libmemcached
pkg install -y redis
pkg install -y mysql80-client
pkg install -y mysql80-server
pkg install -y apache24
pkg install -y php85
pkg install -y mod_php85
pkg install -y php85-bcmath
pkg install -y php85-ctype
pkg install -y php85-curl
pkg install -y php85-dom
pkg install -y php85-extensions
pkg install -y php85-filter
pkg install -y php85-ftp
pkg install -y php85-gd
pkg install -y php85-hash
pkg install -y php85-iconv
pkg install -y php85-imap
pkg install -y php85-json
pkg install -y php85-mbstring
pkg install -y php85-mysqli
pkg install -y php85-opcache
pkg install -y php85-openssl
pkg install -y php85-pdo
pkg install -y php85-pdo_sqlite
pkg install -y php85-phar
pkg install -y php85-posix
pkg install -y php85-session
pkg install -y php85-simplexml
pkg install -y php85-snmp
pkg install -y php85-soap
pkg install -y php85-sockets
pkg install -y php85-sqlite3
pkg install -y php85-tokenizer
pkg install -y php85-xml
pkg install -y php85-xmlreader
pkg install -y php85-xmlwriter
pkg install -y php85-zip
pkg install -y php85-zlib
pkg install -y php85-pecl-memcached
pkg install -y php85-pecl-redis


pkg install -y graphviz
pkg install -y softflowd
pkg install -y sqlite3
pkg install -y sudo
pkg install -y vim-tiny
pkg install -y wget
pkg install -y arping
pkg install -y bandwidthd
pkg install -y elinks
pkg install -y mc
pkg install -y nano
pkg install -y nmap
pkg install -y mtr-nox11
pkg install -y expect
pkg install -y bwm-ng
pkg install -y ifstat
pkg install -y iperf
pkg install -y iperf3
pkg install -y arpwatch
pkg install -y ap24-mod_rpaf2
pkg install -y git
pkg install -y ffmpeg
pkg install -y nginx
pkg install -y bmon
pkg install -y iftop
pkg install -y bind-tools
pkg install -y trafshow
pkg install -y fping
pkg install -y goaccess
pkg install -y bat

#new port tree installation
rm -rf /usr/ports
git clone https://git.FreeBSD.org/ports.git /usr/ports

#freeradius3 required to build with MySQL support
cd /usr/ports/net/freeradius3/ && make WITH="MYSQL USER" BATCH=yes install

#memcached pecl build for PHP 8.3
cd /usr/ports/databases/pecl-memcached &&  make BATCH=yes install



echo "Creating binary packages"
pkg create -a -o ${PKGPATH}
pkg create  -o ${PKGPATH} -g bash
echo "Binary packages created"
cd ${PKGROOT}
echo "Packing binary packages"
tar cf - ${PLATFORM} | gzip > ${ARCHNAME}
echo "Packing binary packages finished: "${PKGROOT}${ARCHNAME}
