#!/bin/sh

if [ $# -ne 1 ]
then
  echo "Usage: sh packagepack_ver \"PLATFORM\""
  echo "Example: sh packagepack_121T 121_6T or sh packagepack_121T 121_3T"
  exit
fi

#bootstraping pkgng
pkg info

PLATFORM=$1
PKGROOT="/home/"
PKGPATH=${PKGROOT}${PLATFORM}
ARCHNAME=${PLATFORM}".tar.gz"

mkdir ${PKGPATH}

#installing packages
pkg install -y bash
pkg install -y expat
pkg install -y gmake
pkg install -y isc-dhcp44-server
pkg install -y libtool
pkg install -y autoconf
pkg install -y memcached
pkg install -y redis
pkg install -y mysql56-client
pkg install -y mysql56-server
pkg install -y apache24
pkg install -y php74
pkg install -y mod_php74
pkg install -y php74-bcmath
pkg install -y php74-ctype
pkg install -y php74-curl
pkg install -y php74-dom
pkg install -y php74-extensions
pkg install -y php74-filter
pkg install -y php74-ftp
pkg install -y php74-gd
pkg install -y php74-hash
pkg install -y php74-iconv
pkg install -y php74-imap
pkg install -y php74-json
pkg install -y php74-mbstring
pkg install -y php74-mysqli
pkg install -y php74-opcache
pkg install -y php74-openssl
pkg install -y php74-pdo
pkg install -y php74-pdo_sqlite
pkg install -y php74-phar
pkg install -y php74-posix
pkg install -y php74-session
pkg install -y php74-simplexml
pkg install -y php74-snmp
pkg install -y php74-soap
pkg install -y php74-sockets
pkg install -y php74-sqlite3
pkg install -y php74-tokenizer
pkg install -y php74-xml
pkg install -y php74-xmlreader
pkg install -y php74-xmlwriter
pkg install -y php74-zip
pkg install -y php74-zlib
pkg install -y php74-pecl-memcached
pkg install -y php74-pecl-redis


pkg install -y graphviz
pkg install -y softflowd
pkg install -y sqlite3
pkg install -y sudo
pkg install -y vim-tiny
pkg install -y wget
pkg install -y arping
pkg install -y bandwidthd
pkg install -y elinks
pkg install -y mc
pkg install -y nano
pkg install -y nmap
pkg install -y mtr-nox11
pkg install -y expect
pkg install -y bwm-ng
pkg install -y ifstat
pkg install -y iperf
pkg install -y ap24-mod_rpaf2

#freeradius3 required to build with MySQL support
cd /usr/ports/net/freeradius3/ && make WITH="MYSQL USER" BATCH=yes install

#memcached pecl build for PHP 7.4
portsnap fetch && portsnap extract && portsnap update
cd /usr/ports/databases/pecl-memcached &&  make BATCH=yes install



echo "Creating binary packages"
pkg create -a -o ${PKGPATH}
pkg create  -o ${PKGPATH} -g bash
echo "Binary packages created"
cd ${PKGROOT}
echo "Packing binary packages"
tar cf - ${PLATFORM} | gzip > ${ARCHNAME}
echo "Packing binary packages finished: "${PKGROOT}${ARCHNAME}
