#!/bin/sh

LOGIN=$1
IP=$2
CASH=$4
ID=$3

fwcmd="/sbin/ipfw -q"

# TIME FORMAT
cur_date=`date \+\%Y.\%m.\%d`
cur_time=`date \+\%H:\%M:\%S`

# DELETE RULEZ FRO IPFW
${fwcmd} pipe `expr $ID + 101` delete
${fwcmd} pipe `expr $ID + 32101` delete

${fwcmd} table 47 add $IP

${fwcmd} table 3 delete $IP
${fwcmd} table 4 delete $IP


# DAY/NIGHT switcher
/bin/rm /etc/stargazer/dn/$LOGIN


echo "$cur_date $cur_time DISCONNECT: ID-$ID;LOGIN-$LOGIN;IP-$IP;CASH-$CASH" >> /var/stargazer/allconnect.log

